name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3.0.2
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        check-latest: true
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: Lint code
      run: sbt checkFmt      

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        check-latest: true
        cache: 'sbt'
    - name: Run tests
      run: sbt test
      